name: deploy
on: deployment_status
jobs:
  trigger-tests-after-deploy:
    # only runs this job on successful deploy
    # https://glebbahmutov.com/blog/develop-preview-test/
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-20.04
    steps:
      # trigger CircleCI pipeline to run E2E tests
      # https://circleci.com/docs/api/v2/#operation/triggerPipeline
      - name: Trigger CircleCI
        run: |
          echo "Vercel unique deployment URL is ${{ github.event.deployment_status.target_url }}"

          # --silent option to not print request progress
          curl -u ${{ secrets.CIRCLE_CI_API_TOKEN }}: \
            --silent \
            --data parameters[TEST_BRANCH]=${GITHUB_HEAD_REF} \
            --data parameters[TEST_URL]=${{ github.event.deployment_status.target_url }} \
            https://circleci.com/api/v2/project/gh/bahmutov/todomvc-tests-circleci/pipeline
