# every time we open a pull request, or a commit is pushed to it
# Vercel deploys the site to a preview environment
name: pull
on: pull_request
jobs:
  trigger-tests:
    runs-on: ubuntu-20.04
    steps:
      # trigger CircleCI pipeline to run E2E tests
      # https://circleci.com/docs/api/v2/#operation/triggerPipeline

      # the preview URL follows the format:
      # https://<project name>-git-<branch name>-<team name>.vercel.app/
      # https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables
      - name: Trigger CircleCI
        run: |
          export VERCEL_PROJECT_NAME=todomvc-no-tests-vercel
          export VERCEL_TEAM_NAME=gleb-bahmutov
          export PREVIEW_URL=https://${VERCEL_PROJECT_NAME}-git-${GITHUB_HEAD_REF}-${VERCEL_TEAM_NAME}.vercel.app/
          echo "Vercel deployment URL is ${PREVIEW_URL}"

          # --silent option to not print request progress
          curl -u ${{ secrets.CIRCLE_CI_API_TOKEN }}: \
            --silent \
            --data branch=${GITHUB_HEAD_REF} \
            --data parameters[TEST_BRANCH]=${GITHUB_HEAD_REF} \
            --data parameters[TEST_URL]=${PREVIEW_URL} \
            https://circleci.com/api/v2/project/gh/bahmutov/todomvc-tests-circleci/pipeline
